# Generated by Django 5.2.7 on 2025-10-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Arma')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('img', models.URLField(max_length=500, verbose_name='URL de Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Arma',
                'verbose_name_plural': 'Armas',
                'ordering': ['-created'],
            },
        ),
    ]
