# Generated by Django 5.2.7 on 2025-10-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='img',
            field=models.ImageField(upload_to='weapons/', verbose_name='Imagen del Arma'),
        ),
    ]
